version: "2"

networks:
  insideboard:
    driver: bridge

services:
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=data
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data:/data/db
    networks:
      - insideboard
    ports:
      - "27017:27017"

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:5.5.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_K8S:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092,PLAINTEXT_K8S://10.0.2.2:9093
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"

  # prometheus:
  #   image: prom/prometheus:latest
  #   volumes:
  #     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  #   networks:
  #     - insideboard
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   image: grafana/grafana:6.7.3
  #   networks:
  #     - insideboard
  #   ports:
  #     - "3000:3000"

  jaeger:
    image: jaegertracing/all-in-one:1.14
    networks:
      - insideboard
    ports:
      - "14268:14268"
      - "16686:16686"
      - "5775:5775"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "9411:9411"
    environment:
      - "COLLECTOR_ZIPKING_HTTP_PORT=9411"
