apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express-api
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-express-api
  template:
    metadata:
      labels:
        app: node-express-api
    spec:
      containers:
        - image: node-express-api
          name: node-express-api
          imagePullPolicy: Never
          env:
            - name: JAEGER_AGENT_HOST
              value: "10.0.2.2"
            - name: JAEGER_SAMPLER_TYPE
              value: "const"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  namespace: argocd
  name: node-express-api
spec:
  type: NodePort
  selector:
    app: node-express-api
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 31001
# ---
# apiVersion: getambassador.io/v1
# kind: Mapping
# metadata:
#   namespace: minikube
#   name: mapping-training
# spec:
#   prefix: /apis/training/v1
#   service: node-express-api
#   rewrite: /api/v1
